title: ALL GROUP DESIGN AND RESEARCH
email: hello@agdr.com
description: >-
  Personal Design Assistant & Workspace Manager
baseurl: "/site"
url: "https://agdrbkk.github.io"

theme: minima
plugins:
  - jekyll-feed

collections:
  lab:
    output: true
    permalink: /lab/:name/
  work:
    output: true
    permalink: /work/:name/

# Ensure collection items render with a layout by default
defaults:
  - scope:
      path: ""
      type: lab
    values:
      layout: entry
  - scope:
      path: ""
      type: work
    values:
      layout: entry

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - agdr/vendor/

include:
  - _work
  - _lab
  - admin
